### ISSUE TITLE
Write-Progress -Activity Error

### ISSUE THREAD

**Issue by TWDesigns** [gravelfreeman/makemkv-batch#1]
Hello! First and foremost THANK YOU for writing this. I have searched all day, and failed, to find a Batch Script that will work.

1. After running the script I get an "Attempted to divide by 0" error for Line:107 Char:9. 
2. The script still executes and converts my ISO to MKV however on the first ISO it did not keep the same naming convention. The 2nd test ISO saved the filename correctly.

**Comment by TWDesigns** [comment]
Disregard. Running it from IN powershell produces the error. Executing the script normally runs as intended. Tested a different script and had the same naming convention error as here. 

THANK YOU

**Comment by gravelfreeman** [comment]
Glad you got it to work and yes, I believe I've searched the whole internet and this doesn't exist.
